### ISSUE TITLE
Allow users of `DataInspector` to register custom behavior for their types

### ISSUE THREAD

**Issue by roby2014** [GameDevTecnico/cubos#811] opened 2023-11-13 14:34 UTC
#810

**Comment by RiscadoA** [comment] 2024-04-22 08:12
One big problem with this is that this 'custom behavior' might require access to random data in the `World`.
For example, imagine we wanted to add a asset selection popup when modifying `Asset` fields on a component.
To do this, we would need to access the `Assets&` resource in this custom behavior.

This would require us passing `Assets&` to the `inspector.edit` method, which is of course unreasonable. Passing the entire `World` is a more acceptable possibility, but if we go this route, why keep the `DataInspector` as a resource?
I think we can make it a full-fledged system argument entirely (which was implicitly access to the `World`).

Using it would be basically the same:

```cpp
cubos.system("hey").call([](DataInspector inspector) {
  Asset<Foo> foo;
  inspector.edit(foo); // it just works
});
```

**Comment by RiscadoA** [comment] 2024-05-29 14:56
Duplicate of #1179.

**Closed by RiscadoA** 2024-05-29 14:56 UTC
Labels: A-Engine
