### ISSUE TITLE
`tesseratos` crashes when minimizing and opening it again

### ISSUE THREAD

**Issue by roby2014** [GameDevTecnico/cubos#712] opened 2023-10-11 21:16 UTC
# Description

`tesseratos` currently crashes when minimizing and opening it again.

```
[cubos] [ogl_render_device.cpp:1433 cubos::core::gl::OGLRenderDevice::createFramebuffer] error: glCheckFramebufferStatus didn't return GL_FRAMEBUFFER_COMPLETE
[cubos] [ogl_render_device.cpp:1433 cubos::core::gl::OGLRenderDevice::createFramebuffer] error: glCheckFramebufferStatus didn't return GL_FRAMEBUFFER_COMPLETE
[cubos] [ogl_render_device.cpp:1433 cubos::core::gl::OGLRenderDevice::createFramebuffer] error: glCheckFramebufferStatus didn't return GL_FRAMEBUFFER_COMPLETE
[cubos] [ogl_render_device.cpp:1433 cubos::core::gl::OGLRenderDevice::createFramebuffer] error: glCheckFramebufferStatus didn't return GL_FRAMEBUFFER_COMPLETE
Assertion failed: abs(aspect - std::numeric_limits<T>::epsilon()) > static_cast<T>(0), file H:\coding\cubos\core\lib\glm\glm\ext\matrix_clip_space.inl, line 251
```

# Reproduce

https://github.com/GameDevTecnico/cubos/assets/47612455/0f7b6200-1586-44e2-91e9-cca9287c719f

**Comment by RiscadoA** [comment] 2023-10-15 18:06
Duplicate of #479

**Closed by RiscadoA** 2023-10-15 18:06 UTC
Labels: C-Crash
